# Generated by Django 4.2.27 on 2026-01-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('condition', models.CharField(default='Unknown', max_length=50)),
                ('status', models.CharField(default='vacant', max_length=50)),
                ('property_type', models.CharField(default='UNK', max_length=50)),
                ('city', models.CharField(default='Albany', max_length=50)),
            ],
        ),
    ]
