# Generated by Django 4.2.27 on 2026-01-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlipAlbApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sqft',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
