# Generated by Django 4.2.27 on 2026-01-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlipAlbApp", "0003_alter_property_sqft"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="ownerName",
            field=models.CharField(default="None", max_length=50, null=True),
        ),
    ]
